# Generated by Django 3.2.6 on 2021-09-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
