# Generated by Django 3.2.6 on 2021-09-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210905_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
