# Generated by Django 3.2.6 on 2021-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=15, unique=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='tester',
            field=models.CharField(default='', help_text='接口测试人', max_length=13, verbose_name='接口测试人'),
        ),
    ]
